### ISSUE TITLE
Cannot find module '@stencil/core/internal' after upgrade from version 4.3.0 to 5.2.0

### ISSUE THREAD

**Issue by raphaelgodart** [siemens/ix#2730]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [x] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

I've performed the upgrade of our project from Siemens iX 4.3.0 to 5.2.0, by following your upgrade guidelines described here: https://ix.siemens.io/docs/home/migration/5_0_0

The upgrade performed by an AI agent and was successfully executed and the project starts up. However, after the upgrade by the AI agent, I noticed that the following entry was added to the `compilerOptions` array of our project's `tsconfig.json`:

```
"skipLibCheck": true
```

I wondered why this is necessary and removed it. After removing it, the project fails to start up and throws this error:

```
TS2307: Cannot find module '@stencil/core/internal' 
```

Why is this happening? Is it expected that we add `"skipLibCheck": true`to tsconfig.json in order to avoid this error?

### What type of frontend framework are you seeing the problem on?

Angular (Standalone)

### On which version of the frontend framework are you experiencing the issue?

@angular/core@20.3.24

### Which version of iX do you use?

v5.2.0

### Code to produce this issue.

```shell
https://stackblitz.com/edit/stackblitz-starters-fwthbfuy?file=src%2Fmain.ts
```

**Comment by benjgil** [comment]
@raphaelgodart are you referencing @stencil/core/internal in your project?

**Comment by raphaelgodart** [comment]
@benjgil No we don't reference @stencil/core/internal in our project. Is this a requirement for installing Siemens iX 5? I haven't seen any mention of that in the upgrade and breaking changes guides. Wouldn't it be strange that a project must reference a Siemens iX peer dependency directly?

**Comment by benjgil** [comment]
Hi @raphaelgodart 
Apologies for the delay in responding.
No you shouldn't need to reference it anywhere for any IX version. We have an erroneous reference to it in our types files which shouldnt be there. We are fixing for version 6.
In the meanwhile you can fix this locally by adding @stencil/core to the devDependencies of your project, which is preferable to the tsconfig flag that can potentially hide issues elsewhere in your project.

**Comment by raphaelgodart** [comment]
Hi @benjgil, thanks for the info. We've added it to our devDependencies until the issue is resolved upstream.
