### ISSUE TITLE
showToast is not a function in Production Build - Angular

### ISSUE THREAD

**Issue by kghandour** [siemens/ix#1999]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [x] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

The fix introduced in https://github.com/siemens/ix/pull/1921 to tackle #1911 did not fix the problem with the toasts. 
Currently in development environment, toasts are working as expected. When building to production, after viewing the built website, whenever a toast should show, I am getting this error in the dev console

```
Jo(...).showToast is not a function
```

### What type of frontend framework are you seeing the problem on?

Angular (Standalone)

### On which version of the frontend framework are you experiencing the issue?

@angular/core@19.2.2

### Which version of iX do you use?

v3.1.1

### Code to produce this issue.

```shell
export class ToastExampleComponent {
    toastService = inject(ToastService)

    onclick(){
          this.toastService.show({
            message: 'Success',
            type: 'success',
          })
    }
}



Build with 

 ng build -c production
```

**Comment by danielleroux** [comment]
@kghandour I can not reproduce it on my side (angular 20). 

```
import { Component, inject, signal } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { IxButton, ToastService } from '@siemens/ix-angular/standalone';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, IxButton],
  providers: [ToastService],
  template: '<ix-button (click)="trigger()">Trigger</ix-button>',
  styleUrl: './app.css',
})
export class App {
  protected readonly title = signal('angulartest');

  private toastService = inject(ToastService);

  trigger() {
    this.toastService.show({
      title: 'Toast triggered',
      message: 'This is a toast message.',
      type: 'info',
    });
  }
}
```


Please provide a complete github repo where I can see the issue.

**Comment by schaefer-austin-p-siemens** [comment]
@danielleroux based on your statement, you attempted to reproduce on Angular 20, when OP stated Angular 19.

Regardless: I'm experiencing the same issue on both 19 and 20. 

Example is located at [this example Github Repo](https://github.com/schaefer-austin-p-siemens/siemens-ix-bug-toast-service).

Screenshots of failing state: 

Chrome:

<img width="1916" height="1079" alt="Image" src="https://github.com/user-attachments/assets/8ccb519b-b162-4d30-950d-e8c474053cc2" />

Firefox:

<img width="1869" height="1079" alt="Image" src="https://github.com/user-attachments/assets/ffbd92a5-c67f-4d15-a714-40a98be4600e" />

**Comment by schaefer-austin-p-siemens** [comment]
This issue exists for me as well on a company internal project.

**Comment by GayatriK2002** [comment]
Hi, I am able to reproduce this issue, and we are analyzing it. We will update soon about it.
<img width="1909" height="370" alt="Image" src="https://github.com/user-attachments/assets/562d1ab1-d4a2-4755-81e3-7fbcde7c15fa" />

**Comment by fine-simple** [comment]
If it helps finding the root cause it also happens in my React App, the toast works find in development, but the function isn't found in production

**Comment by GayatriK2002** [comment]
Hi @kghandour 
Workaround for this issue:
Import and call defineCustomElements() from @siemens/ix/loader before bootstrapping the Angular application. This ensures iX web components are properly registered before they're used, preventing issues caused by tree-shaking in production builds.

Another work around is import ToastService from standalone in your app.component.ts file as follows -
import { ToastService } from '@siemens/ix-angular/standalone';

You can use this work around, we will soon fix this issue from our side.

<img width="712" height="323" alt="Image" src="https://github.com/user-attachments/assets/0b1f320a-9337-4849-857c-97fcccd05252" />

<img width="678" height="582" alt="Image" src="https://github.com/user-attachments/assets/402de6d4-e934-49da-93a3-586185988ca0" />

**Comment by GayatriK2002** [comment]
Hi @fine-simple ,
I've tested the toast component in React and it's working fine in both development and production modes on my end. Could you share more details about your specific setup (React version, build tool) and any error messages you're seeing? A small code snippet would also help us identify why it's occurring in your environment specifically.

**Comment by schaefer-austin-p-siemens** [comment]
Went to bat on this again in my team's project: much like @GayatriK2002 mentioned, it was necessary to add `providers: [ToastService]` within the `@Component` annotation, which isn't mentioned in the [Angular Standalone example documentation](https://ix.siemens.io/docs/components/toast/code)I for toasts. I also had to double check to ensure the standalone version of the ToastService was being imported instead of the modules version; this can occur quite frequently when devs use the IDE auto imports or quick fixes to import the dependency, as opposed to typing it out: it may be worth further splitting the ng modules siemens ix away from the standalone one from this perspective.

**Comment by kghandour** [comment]
We fixed this in our project by adding ToastService as a provider where we use ToastService. But I agree with @schaefer-austin-p-siemens . It is not clearly visible in the code example. Only got that working thanks to @danielleroux 's example.

It is a bit tricky that tree shaking could cause something to work well in development environment but not in production. Thanks for your help.

**Comment by hanneslueke** [comment]
I've encountered that problem as well But it appears only if you enable the build optimization in angluar.

**Comment by dennis-kaminski-cp** [comment]
I’m experiencing the same issue in our React SPA using Vite as bundler.

Everything works fine in development, but in production builds the following error appears when the toast function is called:

```javascript
toast.success({ message: 'my message' });
```

```
Uncaught (in promise) TypeError: ZJ(...).showToast is not a function
    at ua (VM106:408:18757)
    at Object.onSuccess (VM106:441:97839)
    at fse.execute (VM106:441:41831)
```
Environment:
```json
"@siemens/ix": "^3.2.0"
"@siemens/ix-react": "^3.2.0",
"react": "^19.1.0",
"react-dom": "^19.1.0",
"vite": "^7.0.4",
```

The workaround solved the issue:
```javascript
import { defineCustomElements } from '@siemens/ix/loader';
defineCustomElements();
```

**Comment by GayatriK2002** [comment]
When using ToastService in Angular Standalone components, you must add ToastService to the providers array in your component decorator to ensure proper functionality in production builds. I have updated the same in PR which will update the examples in documentation.

**Comment by NiklasHae** [comment]
We introduced a custom eslint rule to avoid accidentally importing the wrong version of the `ToastService`, as we only notice this issue when running the production build. Most of the editors will pick the wrong one right now when using auto imports.

```json
"no-restricted-imports": ["error", {
  "paths": [{
    "name": "@siemens/ix-angular",
    "importNames": ["ToastService"],
    "message": "Please use standalone imports instead (e.g. @siemens/ix-angular/standalone)"
  }]
}]
```

Feel free to make use of it in your projects.
